### ISSUE TITLE
Ajax Error because of get_current_screen() call

### ISSUE THREAD

**Issue by aminta** [Kuuak/woo-default-attributes#1]
In `public function get_post_metadata( $value, $object_id, $meta_key ) ` 

`
$screen = get_current_screen();
				if ( 'add' === $screen->action ) // [etc...]
`

determines a "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" in console and when you try to add via select a new custom attribute the wheel spins infinitely and you get "load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,underscore,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,backbone,wp-util,&load[]=wp-backbone,media-models,plupload&ver=4.7.9:4 POST http://websiteaddress.com/wp-admin/admin-ajax.php 500 (Internal Server Error)" in console

If you delete the ` get_current_screen()` all works!

**Comment by cheadrian** [comment]
I can confirm. Removing that and the if after fixed the problem.

**Comment by kuuak** [comment]
Thanks guys,
The bug is fixed https://github.com/Kuuak/woo-default-attributes/commit/94ff5e923cacf7b408dcd524305ea13149ebf5c9 and released under v1.0.3.
